import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, FileText, Download, Activity, Droplets, Leaf } from 'lucide-react';

interface ReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  plantName: string;
  image: string;
  diagnosis: string;
  healthScore: number;
}

export function ReportModal({ isOpen, onClose, plantName, image, diagnosis, healthScore }: ReportModalProps) {
  if (!isOpen) return null;

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
        <motion.div 
          initial={{ opacity: 0, y: 50, scale: 0.95 }}
          animate={{ opacity: 1, y: 0, scale: 1 }}
          exit={{ opacity: 0, y: 20, scale: 0.95 }}
          className="w-full max-w-2xl bg-card border border-border rounded-3xl overflow-hidden shadow-2xl relative max-h-[90vh] flex flex-col"
        >
          {/* Header */}
          <div className="flex items-center justify-between p-6 border-b border-white/10 bg-black/20">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-accent/20 flex items-center justify-center border border-accent/30">
                <FileText className="w-5 h-5 text-accent" />
              </div>
              <div>
                <h2 className="text-xl font-semibold text-white">Diagnostic Report</h2>
                <p className="text-sm text-gray-400">Generated by Plantiva AI</p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <button 
                className="px-4 py-2 bg-white/10 hover:bg-white/20 text-white rounded-lg text-sm font-medium transition-colors flex items-center gap-2 border border-white/10"
                onClick={() => window.print()}
              >
                <Download className="w-4 h-4" />
                Export PDF
              </button>
              <button 
                onClick={onClose}
                className="w-10 h-10 bg-black/50 hover:bg-black/80 rounded-full flex items-center justify-center text-white/70 hover:text-white transition-colors"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
          </div>

          {/* Content */}
          <div className="p-6 overflow-y-auto custom-scrollbar flex-1 space-y-6">
            
            <div className="flex gap-6">
              <div className="w-32 h-32 rounded-2xl overflow-hidden border border-white/10 shrink-0 bg-black/50">
                <img src={image} alt="Scanned Plant" className="w-full h-full object-cover" />
              </div>
              <div>
                <h3 className="text-2xl font-bold text-white mb-1">{plantName}</h3>
                <p className="text-accent font-medium mb-4">Analysis Complete</p>
                
                <div className="flex gap-4">
                  <div className="px-4 py-2 bg-white/5 rounded-xl border border-white/10 flex items-center gap-2">
                    <Activity className="w-4 h-4 text-blue-400" />
                    <div>
                      <p className="text-[10px] text-gray-400 uppercase tracking-wider">Health Score</p>
                      <p className="text-sm font-semibold text-white">{healthScore}%</p>
                    </div>
                  </div>
                  <div className="px-4 py-2 bg-white/5 rounded-xl border border-white/10 flex items-center gap-2">
                    <Droplets className="w-4 h-4 text-cyan-400" />
                    <div>
                      <p className="text-[10px] text-gray-400 uppercase tracking-wider">Moisture</p>
                      <p className="text-sm font-semibold text-white">Needs Check</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="space-y-4">
              <div className="p-5 rounded-2xl bg-white/5 border border-white/10">
                <h4 className="text-sm font-semibold text-white mb-2 flex items-center gap-2">
                  <Leaf className="w-4 h-4 text-accent" />
                  AI Findings & Diagnosis
                </h4>
                <p className="text-sm text-gray-300 leading-relaxed whitespace-pre-wrap">
                  {diagnosis}
                </p>
              </div>

              <div className="p-5 rounded-2xl bg-accent/10 border border-accent/20">
                <h4 className="text-sm font-semibold text-accent mb-2">Recommended Care Tasks Generated</h4>
                <ul className="text-sm text-gray-300 space-y-2 list-disc pl-4 marker:text-accent">
                  <li>Adjust watering schedule based on AI moisture analysis.</li>
                  <li>Monitor health trends daily via the Dashboard.</li>
                  <li>Check Plant Care Schedule for your newly created tasks.</li>
                </ul>
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
